### ISSUE TITLE
`get` fails on Redis::Future

### ISSUE THREAD

**Issue by ChaoticBoredom** [redis-store/redis-store#272] opened 2016-10-12 17:56 UTC
We're using redis-store for our connections, and keep getting the following error:

```
/.rvm/gems/ruby-2.3.1/gems/redis-store-1.3.0/lib/redis/store/marshalling.rb:43:in `_unmarshal'
/.rvm/gems/ruby-2.3.1/gems/redis-store-1.3.0/lib/redis/store/marshalling.rb:17:in `get'
/.rvm/gems/ruby-2.3.1/gems/redis-store-1.3.0/lib/redis/store/namespace.rb:23:in `block in get'
/.rvm/gems/ruby-2.3.1/gems/redis-store-1.3.0/lib/redis/store/namespace.rb:84:in `namespace'
/.rvm/gems/ruby-2.3.1/gems/redis-store-1.3.0/lib/redis/store/namespace.rb:23:in `get'
```

I've dug into it, and the `get` is returning a `Redis::Future` object, which has no size method and causes the `unmarshal?` to fail.

There was a similar issue in the redis-activesupport repo, but they resolved it by moving code about, rather than what appears to be the underlying issue. ([Issue here](https://github.com/redis-store/redis-activesupport/issues/46) and [PR here](https://github.com/redis-store/redis-activesupport/pull/51))

Any help/resolution w/ this would be greatly appreciated.

**Comment by tubbo** [comment] 2016-10-12 18:42
How are you getting to this? Is it application code using redis-store directly, or are you using some other gem (like redis-rails or redis-sinatra) that delegates its work to redis-store?

**Comment by ChaoticBoredom** [comment] 2016-10-12 18:46
We are creating a connection pool for redis using Redis::Store, and the error is then thrown by sidekiq-pro when we try to make use of the batch functionality.

**Comment by tubbo** [comment] 2016-10-12 19:02
OK...I think this is where the divergence is occurring: https://github.com/redis-store/redis-activesupport/blob/master/lib/active_support/cache/redis_store.rb#L40-L52

When you're not using a ConnectionPool, the `with` method just calls the block given to it, and passes in the `@data`, the redis-store. Otherwise, it basically delegates the logic to `@data`, which in this case should be set to a ConnectionPool instance.

Posting how you've configured redis-store with a connection pool would be really helpful in diagnosing where this issue is coming from.

**Comment by ChaoticBoredom** [comment] 2016-10-12 19:11
Our redis pool set-up:
```
  CACHE_NAMESPACE = 'redis_rails_cache'
  REDIS_POOL_SIZE = Rails.configuration.x.redis_pool

  def self.redis_pool
    redis_conn = proc {
      Redis::Store.new
    }

    @redis_pool ||= ConnectionPool.new(
      :size => REDIS_POOL_SIZE,
      &redis_conn
    )
  end

  def self.namespaced_redis_from_pool
    redis_pool.with do |conn|
      conn.with_namespace(CACHE_NAMESPACE) do
        yield conn
      end
    end
  end
```

We've then set up our sidekiq workers to use the above defined pool (along w/ all of our internal redis caching)

**Comment by tubbo** [comment] 2016-10-12 19:28
One thing that jumps out at me is that you're using `Redis::Store.new`
and not `Redis::Store::Factory.create`, which is what we use in
redis-activesupport...I can take a look in a little bit, but I just
wanted you to be aware of that. Does switching that call to
`Redis::Store::Factory.create` do anything differently?

On 10/12, Susan Wright wrote:
> Our redis pool set-up:
> ```
>   CACHE_NAMESPACE = 'redis_rails_cache'
>   REDIS_POOL_SIZE = Rails.configuration.x.redis_pool
> 
>   def self.redis_pool
>     redis_conn = proc {
>       Redis::Store.new
>     }
> 
>     @redis_pool ||= ConnectionPool.new(
>       :size => REDIS_POOL_SIZE,
>       &redis_conn
>     )
>   end
> 
>   def self.namespaced_redis_from_pool
>     redis_pool.with do |conn|
>       conn.with_namespace(CACHE_NAMESPACE) do
>         yield conn
>       end
>     end
>   end
> ```
> 
> We've then set up our sidekiq workers to use the above defined pool (along w/ all of our internal redis caching)
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/redis-store/redis-store/issues/272#issuecomment-253309340

-- 
- T

**Comment by ChaoticBoredom** [comment] 2016-10-12 19:37
Testing w/ `Redis::Store::Factory.create` throws the same error.

**Comment by ChaoticBoredom** [comment] 2017-01-28 23:20
This is still an issue for us, has there been any changes or is there any additional info needed?

**Comment by tubbo** [comment] 2017-01-30 17:28
@ChaoticBoredom Are you getting any more of a backtrace than what you showed? Your error doesn't include a message or the top of the backtrace, so it's difficult to determine what exactly is going wrong here.

**Comment by ChaoticBoredom** [comment] 2017-01-30 17:31
```
2017-01-30T17:29:37.962Z 47315 TID-owzqrqtwo VisitRenamerWorker JID-254ef6caad04151d4082b510 BID-L5kSfiHi2WZiow INFO: fail: 0.084 sec
2017-01-30T17:29:37.962Z 47315 TID-owzqrqtwo WARN: {"class":"VisitRenamerWorker","args":[{"user_context":{"user_id":27,"account_id":1,"user_name":"Susan Wright","request_id":null,"request_ip":null}},2],"retry":true,"queue":"renamer","jid":"254ef6caad04151d4082b510","created_at":1485797377.444524,"bid":"L5kSfiHi2WZiow","enqueued_at":1485797377.450047,"error_message":"undefined method `size' for <Redis::Future [:get, \"b-L5kSfiHi2WZiow-notify\"]>:Redis::Future","error_class":"NoMethodError","failed_at":1485797377.9625201,"retry_count":0}
2017-01-30T17:29:37.963Z 47315 TID-owzqrqtwo WARN: NoMethodError: undefined method `size' for <Redis::Future [:get, "b-L5kSfiHi2WZiow-notify"]>:Redis::Future
2017-01-30T17:29:37.963Z 47315 TID-owzqrqtwo WARN: /Users/swright/.rvm/gems/ruby-2.3.1/gems/redis-store-1.3.0/lib/redis/store/marshalling.rb:51:in `unmarshal?'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/redis-store-1.3.0/lib/redis/store/marshalling.rb:43:in `_unmarshal'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/redis-store-1.3.0/lib/redis/store/marshalling.rb:17:in `get'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/redis-store-1.3.0/lib/redis/store/namespace.rb:23:in `block in get'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/redis-store-1.3.0/lib/redis/store/namespace.rb:84:in `namespace'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/redis-store-1.3.0/lib/redis/store/namespace.rb:23:in `get'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/sidekiq-pro-3.2.1/lib/sidekiq/batch/middleware.rb:102:in `block (2 levels) in add_failure'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/redis-3.3.1/lib/redis.rb:2298:in `block in multi'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/redis-3.3.1/lib/redis.rb:58:in `block in synchronize'
/Users/swright/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/redis-3.3.1/lib/redis.rb:58:in `synchronize'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/redis-3.3.1/lib/redis.rb:2291:in `multi'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/sidekiq-pro-3.2.1/lib/sidekiq/batch/middleware.rb:100:in `block in add_failure'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/sidekiq-4.1.3/lib/sidekiq.rb:92:in `block in redis'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/connection_pool-2.2.0/lib/connection_pool.rb:64:in `block (2 levels) in with'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `handle_interrupt'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `block in with'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `handle_interrupt'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/sidekiq-4.1.3/lib/sidekiq.rb:89:in `redis'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/sidekiq-pro-3.2.1/lib/sidekiq/batch.rb:35:in `block in redis'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/sidekiq-pro-3.2.1/lib/sidekiq/shard_set.rb:59:in `on'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/sidekiq-pro-3.2.1/lib/sidekiq/batch.rb:34:in `redis'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/sidekiq-pro-3.2.1/lib/sidekiq/batch/middleware.rb:99:in `add_failure'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/sidekiq-pro-3.2.1/lib/sidekiq/batch/middleware.rb:29:in `rescue in call'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/sidekiq-pro-3.2.1/lib/sidekiq/batch/middleware.rb:25:in `call'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/sidekiq-4.1.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/sidekiq-4.1.3/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/sidekiq-4.1.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/sidekiq-4.1.3/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/sidekiq-4.1.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/sidekiq-4.1.3/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/sidekiq-4.1.3/lib/sidekiq/logging.rb:32:in `with_context'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/sidekiq-4.1.3/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/sidekiq-4.1.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/sidekiq-4.1.3/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/sidekiq-4.1.3/lib/sidekiq/processor.rb:129:in `block in process'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/sidekiq-4.1.3/lib/sidekiq/processor.rb:168:in `stats'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/sidekiq-4.1.3/lib/sidekiq/processor.rb:128:in `process'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/sidekiq-4.1.3/lib/sidekiq/processor.rb:80:in `process_one'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/sidekiq-4.1.3/lib/sidekiq/processor.rb:68:in `run'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/sidekiq-4.1.3/lib/sidekiq/util.rb:17:in `watchdog'
/Users/swright/.rvm/gems/ruby-2.3.1/gems/sidekiq-4.1.3/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

Here's the full backtrace from one of the workers in sidekiq. Not sure if there's anything more I can give you, but please let me know.

**Comment by tubbo** [comment] 2017-01-30 18:26
Yes, thank you. I'll review this and get back to you momentarily.

**Comment by ChaoticBoredom** [comment] 2017-03-10 18:43
Is this still in progress?

**Comment by tubbo** [comment] 2017-03-13 21:02
@ChaoticBoredom I'm still trying to reproduce it

**Comment by snwfog** [comment] 2017-05-19 02:41
Problem is caused by Sikdekiq Web UI fetching keys that do not existing in Redis using pipeline.
The error can be reproduced with:
```
ruby -rredis-store -e 'Redis::Store.new.pipelined { |conn | conn.get(%q(lol)) }'
```
I believe if you are using Sidekiq UI then you can turned off marshalling, because data are stored as JSON in Redis. You can can turn off marshalling using `marshalling: false`.

**Comment by tubbo** [comment] 2017-07-10 18:00
Thanks @snwfog, and apologies @ChaoticBoredom for this taking so long...but thank you for being patient. I'll have a fix for this momentarily, you should be able to use marshalling while also using Sidekiq UI...

**Comment by tubbo** [comment] 2017-07-18 14:40
When trying to resolve this in my test, I kept receiving errors based on the fact that a `Redis::Future` object doesn't represent an actual value. Trying to solve the error in this ticket produced another one in the test, because I called `#value` before it was actually set:

```ruby
  1) Error:
Redis::Marshalling#test_0001_unmarshals on get:
Redis::FutureNotReady: Value will be available once the pipeline executes.
```

I don't believe there's a good solution for this unless the semantics of `Redis::Future` change.

**Closed by tubbo** 2017-07-18 14:40 UTC
