### ISSUE TITLE
Please publish a new version to rubygems 

### ISSUE THREAD

**Issue by softbrada** [redis-store/redis-store#352] opened 2022-10-27 09:15 UTC
Currently in master the dependency for redis is relaxed to allow redis v5.x but the latest version is 1.9.1 which has restricted redis below version 5.x 
Can a new gem be published please? I really need redis v5.x

**Comment by tubbo** [comment] 2022-11-07 03:14
@softbrada We're working on a quick bug that I think might preclude that release but I'll put something together this week. Shouldn't take too long. (famous last words)

**Comment by brunoqcx** [comment] 2022-12-15 20:46
hey, upvoting  this, bundler audit is now complaining at redis-store 1.3.0 (the one from a long time ago that did not locked the redis to a maximum version) and this is causing kinda of a dependency hell for me atm  XD

**Comment by gingerlime** [comment] 2022-12-19 06:51
Bumped into the same issue. Upgrading redis to v5 now downgrades redis-store to 1.3.0 to meet the dependency issue (1.3.0 has a more relaxed dependency on `redis >= 2.2`)

**Comment by morimorihoge** [comment] 2022-12-19 23:50
I've got same problem caused by redis-actionpack dependency.

**Comment by gotkaren** [comment] 2023-01-12 15:22
Same problem over here 🙏

**Comment by honkimi** [comment] 2023-02-17 03:14
Currently, I'm setting the redis version.

gem "redis", '4.7.1'

**Comment by HarlemSquirrel** [comment] 2023-02-17 17:04
Seems like this happened a few weeks ago https://rubygems.org/gems/redis-store/versions/1.9.1

**Comment by blerchin** [comment] 2023-02-21 19:13
@tubbo Bumping this thread. Any possibility of a release to address this? Even a hotfix so we could have the benefit of https://github.com/redis-store/redis-store/commit/059b3188042670204ce4d8537231a70c544cc662 would be hugely helpful.

**Comment by rwojsznis** [comment] 2023-02-22 07:14
Semi related: in case you're looking for alternative for Rails - [there is this gem](https://github.com/roidrage/redis-session-store) - it's not a drop-in replacement exactly as it uses different redis key underneath for the session storage, but I can confirm it works fine wit redis 5 (tested with a small+ size production app)

**Comment by tubbo** [comment] 2023-02-24 03:18
@blerchin hey sorry about that, `v1.9.2` should be out momentarily addressing these issues.

@rwojsznis fwiw, that gem is only for rails session storage in particular, and this gem is the underlying library for a few other libraries, including `redis-rack-cache`.

**Comment by tubbo** [comment] 2023-02-24 03:29
`v1.9.2` is out! closing this as completed. https://github.com/redis-store/redis-store/releases/tag/v1.9.2

**Closed by tubbo** 2023-02-24 03:29 UTC

**Comment by softbrada** [comment] 2023-02-24 07:33
Thank you very much :)
