### ISSUE TITLE
NameError: uninitialized constant on Uploader having nothing to do with method

### ISSUE THREAD

**Issue by choonggg** [redis-store/redis-store#281] opened 2017-04-04 13:14 UTC
I'm getting an error using redis-store with error

And it has absolutely no relations to the cache method throwing the error.

```
    Rails.cache.fetch("#{cache_key}/model", expires_in: 1.day) {
      self.model.find_by(currency: currency)
    }
```

### Error thrown

NameError: uninitialized constant ProfilePhotoUploader::Uploader86587360

```
…/gems/redis-store-1.1.7/lib/redis/store/
marshalling.rb:  33:in `_unmarshal'
…/gems/redis-store-1.1.7/lib/redis/store/
marshalling.rb:  17:in `get'
….0/gems/redis-store-1.1.7/lib/redis/store/
namespace.rb:  21:in `block in get'
….0/gems/redis-store-1.1.7/lib/redis/store/
namespace.rb:  74:in `namespace'
….0/gems/redis-store-1.1.7/lib/redis/store/
namespace.rb:  21:in `get'
…esupport-4.1.5/lib/active_support/cache/
redis_store.rb: 230:in `block in read_entry'
…esupport-4.1.5/lib/active_support/cache/
redis_store.rb: 212:in `with'
…esupport-4.1.5/lib/active_support/cache/
redis_store.rb: 230:in `read_entry'
…web_head/releases/20170404092336/app/models/
listing.rb: 252:in `cached_listing_total'
…20170404092336/app/services/listing/
pricing_service.rb:  21:in `total'
…web_head/releases/20170404092336/app/models/
listing.rb: 232:in `i18n_total'
…/ruby/2.3.0/gems/draper-1.4.0/lib/draper/
delegation.rb:  10:in `i18n_total'
….3.0/gems/actionview-4.2.8/lib/action_view/
template.rb: 145:in `block in render'
….3.0/gems/actionview-4.2.8/lib/action_view/
template.rb: 333:in `instrument'
….3.0/gems/actionview-4.2.8/lib/action_view/
template.rb: 143:in `render'
…iew-4.2.8/lib/action_view/renderer/
partial_renderer.rb: 339:in `render_partial'
…iew-4.2.8/lib/action_view/renderer/
partial_renderer.rb: 310:in `block in render'
…ew-4.2.8/lib/action_view/renderer/
abstract_renderer.rb:  39:in `block in instrument'
…ew-4.2.8/lib/action_view/renderer/
abstract_renderer.rb:  39:in `instrument'
…iew-4.2.8/lib/action_view/renderer/
partial_renderer.rb: 309:in `render'
…/actionview-4.2.8/lib/action_view/renderer/
renderer.rb:  51:in `render_partial'
…view-4.2.8/lib/action_view/helpers/
rendering_helper.rb:  35:in `render'
….3.0/gems/actionview-4.2.8/lib/action_view/
template.rb: 145:in `block in render'
….3.0/gems/actionview-4.2.8/lib/action_view/
template.rb: 333:in `instrument'
….3.0/gems/actionview-4.2.8/lib/action_view/
template.rb: 143:in `render'
…iew-4.2.8/lib/action_view/renderer/
partial_renderer.rb: 339:in `render_partial'
…iew-4.2.8/lib/action_view/renderer/
partial_renderer.rb: 310:in `block in render'
…ew-4.2.8/lib/action_view/renderer/
abstract_renderer.rb:  39:in `block in instrument'
…ew-4.2.8/lib/action_view/renderer/
abstract_renderer.rb:  39:in `instrument'
```

**Comment by tubbo** [comment] 2017-04-04 16:19
@choonggg This looks like an issue with something you have in the cache, like the `ProfilePhotoUploader::Uploader` is not a defined constant anymore. Did you change the name of the constant at some point between the time that data was written to the cache and when it was read out of it?

Also, I would check if this class also has some custom marshalling logic applied to it. Any object in Ruby can customize how it's marshalled by [defining some the marshal_dump and/or marshal_load methods](https://ruby-doc.org/core-2.2.2/Marshal.html#module-Marshal-label-marshal_dump+and+marshal_load), so it's possible this class has some broken logic in there?

I'm grasping at straws here because this seems like a very specific circumstance. Can you reproduce the issue at all with a different object? Does this error keep happening or is it only this single case?

**Comment by choonggg** [comment] 2017-04-05 02:08
hi @tubbo, the uploader haven't been changed and doesn't seem like the object implemented any custom marshal methods (using carrierwave).

it's been happening to all my uploaders though and even though the object that was cached has nothing in relation to my uploaders.

**Comment by tubbo** [comment] 2017-04-06 16:28
@choonggg What object is `self.model.find_by(currency: currency)` supposed to be returning?

**Comment by tubbo** [comment] 2017-04-07 13:54
@choonggg I forgot about this...You can also try passing `marshalling: false` into the redis-store client options and see if that fixes anything? That will prevent Redis from trying to marshall the data and allow you to do it yourself.

**Comment by choonggg** [comment] 2017-04-07 15:06
@tubbo, it returns an active record object. Maybe it's just not ideal storing objects into redis cache store. I'll have to stick to json. Rails memory cache store works though.

**Comment by tubbo** [comment] 2017-04-07 18:45
A better test would be to see if MemCacheStore (which uses Dalli) would work, since the Rails in-memory cache store just saves the Ruby object to a `@data` hash and doesn't perform any marshalling.

**Comment by tubbo** [comment] 2017-04-21 16:32
hey @choonggg did you ever test `MemCacheStore` to see if the same thing happens?

**Comment by tubbo** [comment] 2017-07-05 17:25
@choonggg I'm gonna close this since you seem to have resolved it?

**Closed by tubbo** 2017-07-05 17:25 UTC

**Comment by joshua5201** [comment] 2017-08-18 03:12
Hi
I have the same issue here. Both redis and memcached have this issue. 

If I cache any models with Carrierwave uploader, or any models that have relation with them. Then perform a server restart, Rails can't restore the marshalled objects.
Maybe the problem is that Carrierwave create classes like CarrierWave::Storage::File:0x00000007a61880 when read a string (file path) from database, and store an instance of that class to related model fields.

I think this is Carrierwave's issue
https://github.com/carrierwaveuploader/carrierwave/issues/1001
https://github.com/carrierwaveuploader/carrierwave/issues/793
and they seem not to change the design.

**Comment by choonggg** [comment] 2017-08-18 06:14
@tubbo apologies, I totally missed this conversaion, yes I resorted to storing the data in json format instead of relying on marshalling to retrieve the object.

@joshua5201 you will have to store the model in another format (json) or prevent the file attribute from being stored until there's a good serializer for uploader object.
